const defaultListing = {
    action: '',
    sku: '',
    building_type: '',
    postType: '',
    postFrom: '',
    ostAcceptAgent: '',
    zoneId: '',
    projectId: '',
    titleTH: '',
    contentTH: '',
    titleEN: '',
    contentEN: '',
    price: '',
    areaSize: '',
    area_rai: '',
    area_ngan: '',
    area_wa: '',
    floor: '',
    room: '',
    bathroom: '',
    pet_allowed: '',
    fq: '',
    youtube: '',
    latitude: '',
    longitude: '',
    picture1: '',
    picture2: '',
    picture3: '',
    picture4: '',
    picture5: '',
    picture6: '',
    picture7: '',
    picture8: '',
    picture9: '',
    picture10: '',
    picture11: '',
    picture12: '',
    usefulSpace: '',
    incomeAvgPerYear: '',
    email: '',
    lineId: '',
    tel: '',
    name: '',
    whatsapp: '',
    facebookMessenger: '',
    wechat: '',
    externalDataSource: '',
    facingDirection: '',
    unitNumber: '',
    psCode: '',
    area: '',
    avlChecked: '',
}

module.exports = {
    defaultListing
}
