const REPORT_STATUS = {
    SUCCESS: 'SUCCESS',
    ERROR: 'ERROR',
    DUPLICATED: 'DUPLICATED',
    OK: 'Ok',
    SKIPPED: 'SKIPPED',
    DATA_NOT_FOUND: 'DATA NOT FOUND',
    IMAGE_NOT_FOUND: 'IMAGE NOT FOUND',
}

module.exports = {
    REPORT_STATUS
}
